[build]
base = "."
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
package = "netlify-plugin-bundle-env"
  [plugins.inputs]
  directories = ["."]
  include = ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx"]
