[build]
  command = "pnpm install --frozen-lockfile && pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Use Netlify's built-in Next.js support
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Prerender = "false"

# VGS Integration is managed through the Netlify UI
# See vgs-integration-notes.md for details
