[build]
  command = "pnpm install --no-frozen-lockfile && npm run build"
  publish = "."

[build.environment]
  NODE_VERSION = "20.0.0"
  NPM_VERSION = "9.6.7"
  NPM_FLAGS = "--no-frozen-lockfile"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
