[build]
base = "."
command = "pnpm install --no-frozen-lockfile && pnpm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "22.13.0"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
package = "netlify-plugin-bundle-env"
  [plugins.inputs]
  source = "netlify/functions"
  include = [
    "NEXT_PUBLIC_API_URL",
    "NEXT_PUBLIC_FIREBASE_KEY",
    "NEXT_PUBLIC_SENTRY_DSN"
  ]
  mask = true
