[[build]
  command = "pnpm install --no-frozen-lockfile && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.0.0"
  NPM_VERSION = "9.6.7"
  NPM_FLAGS = "--no-frozen-lockfile"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# For Next.js on Netlify, you typically do NOT need a catch-all redirect to index.html.
# The plugin handles routing for you.
# If you are using static export (next export), then the redirect may be needed,
# but for SSR/ISR, remove the following block:

# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
