[build]
  base = ""
  publish = "out"
  command = "pnpm install --frozen-lockfile && pnpm run build"

[build.environment]
  NODE_VERSION = "18"

# VGS Integration is managed through the Netlify UI
# See vgs-integration-notes.md for details
