[build]
  publish = "out"
  command = "pnpm run build"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
package = "netlify-plugin-bundle-env"

# VGS Integration is managed through the Netlify UI
# See vgs-integration-notes.md for details
